settings:
  treasure-amount: 5
  standings-announcement-delay: 1 # In minutes
  lobby-starting-point:
    x: 195
    y: 117
    z: 318
  game-starting-point:
    x: 222
    y: 71
    z: 347
  map-settings:
    map-size:
      x: 200
      z: 200
    map-world: world
    map-height: 100

message:
  noActiveGame:
    - "[message] &cThere is no active game!"
  gameStarted:
    - "[actionbarbroadcast] &fTreasure Hunt &ahas started!"
  alreadyJoined:
    - "[actionbar] &cYou are already in the game!"
  successfullyJoined:
    - "[message] &aYou have successfully joined the &fTreasure Hunt&a!"
  playerFoundTreasure:
    - "[broadcast] &f{player-name} &afound a treasure with &f{treasure-rarity} &ararity!"
    - "[actionbar] &a+{treasure-points} &7points &8(&7Total: &f{user-points}&8)"
    - "[particle] CRIT_MAGIC;{treasure-location}"
  gameFinished:
    - "[broadcast] &aThe game has finished! &7(bellow are the standings)"
    - "[broadcast]  &f%treasurehunt_top-players_1%"
    - "[broadcast]  &f%treasurehunt_top-players_2%"
    - "[broadcast]  &f%treasurehunt_top-players_3%"
  standingsAnnouncement:
    - "[broadcast] &aThe current &fTreasure Hunt &atop &f3 &astandings are as follows:"
    - "[broadcast]  &f%treasurehunt_top-players_1%"
    - "[broadcast]  &f%treasurehunt_top-players_2%"
    - "[broadcast]  &f%treasurehunt_top-players_3%"
