settings:
  treasure-amount: 5 # The amount of treasures spawned that can exist at the same time
  standings-announcement-delay: 1 # The delay in minutes for which the standings should be announced
  lobby-starting-point: # A point where the players get spawned when joining the game
    x: 78.5
    y: 65
    z: 178.5
  game-starting-point: # A point where the players all start from when the game starts
    x: 78.5
    y: 65
    z: 178.5
  map-settings:
    map-size:
      x: 10
      z: 10
    map-world: world
    # World spawn height settings (treasure spawn)
    map-height-max: 66
    map-height-min: 63

treasures:
  chance-range: 1000
  common:
    texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDdlYzQxZTBkZjhlMTcwZDk3ZjliOWFmMWQ2NWVkYWQ0OTc5Yzc4Yzg5YjAxYjE4MGYzODllZTA4YTYxYWY4MiJ9fX0="
    points: 1
    chance: "400;1000"
  rare:
    texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYmE2ZGFjODAzNWQzNjFiYTdmMmMyYTYxNGI0ZWJhYWZjMWU1ZTMxMDFmODViZWVmNjgzNTM2ZjMzN2U1MDkwIn19fQ=="
    points: 2
    chance: "100;400"
  legendary:
    texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMmQwYmRmMzliNTRmNDk2OTJmYjM3OWI0ZWIwNGQxZWI0YTAwZTc4ZWQzOTExYWQzYjYzYTdlNWJmMzE3NjgzNyJ9fX0="
    points: 5
    chance: "0;100"

message:
  noActiveGame:
    - "[message] &cPočakaj da bo na voljo odprta igra!"
  gameStarted:
    - "[delay=1s][actionbarbroadcast] &d| &fEaster Hunt se je začel &d|"
  gameIsActive:
    - "[message] &cNemoreš začeti igre, ker je že aktivna!"
  alreadyJoined:
    - "[actionbarmessage] &cSi že v igri!"
  successfullyJoined:
    - "[message] &aUspešno si se pridružil &fEaster Hunt&a-u!"
  playerFoundTreasure:
    - "[actionbarmessage] &a+{treasure-points} &8(&f{user-points}&8)"
  gameFinished:
    - "[broadcast] &aIgra se je končala! &7(spodaj so rezultati)"
    - "[broadcast]  &f%treasurehunt_top-players_1%"
    - "[broadcast]  &f%treasurehunt_top-players_2%"
    - "[broadcast]  &f%treasurehunt_top-players_3%"
  standingsAnnouncement:
    - "[broadcast] &aTrenutno stanje najboljših &ftreh &aigralcev je:"
    - "[broadcast]  &f%treasurehunt_top-players_1%"
    - "[broadcast]  &f%treasurehunt_top-players_2%"
    - "[broadcast]  &f%treasurehunt_top-players_3%"
